=== vitjasek/Znackovaci_jazyky/SR_schema.xsd
<?xml version="1.0"?>

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="vesmir">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sektor"/>
      </xs:sequence>
      <xs:attribute name="pocet_sektoru" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="sektor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="system" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="nazev_sektoru" type="xs:string" use="required"/>
      <xs:attribute name="pocet_systemu" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="system">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="planeta" maxOccurs="unbounded"/>
        <xs:element ref="pilot" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="nazev_systemu" type="xs:string"/>
      <xs:attribute name="pocet_planet" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="planeta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="obyvatele" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="politika" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="zamereni" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="pilot"  maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="nazev_planety" type="xs:string" use="required"/>
      <xs:attribute name="pocet_obyvatel" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="zamereni">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Zemedelstvi"/>
        <xs:enumeration value="Prumysl"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="politika">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Anarchie"/>
        <xs:enumeration value="Diktatura"/>
        <xs:enumeration value="Monarchie"/>
        <xs:enumeration value="Demokracie"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="rasa">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Galian"/>
        <xs:enumeration value="Feyan"/>
        <xs:enumeration value="Člověk"/>
        <xs:enumeration value="Peleng"/>
        <xs:enumeration value="Maloc"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="obyvatele">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rasa"/>
      </xs:sequence>
      <xs:attribute name="vstah_k_pilotovi" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="pilot">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="jmeno" type="xs:string"/>
        <xs:element ref="rank"/>
        <xs:element ref="rasa"/>
        <xs:element ref="rating"/>
        <xs:element ref="role"/>
        <xs:element ref="vesmirna_lod"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="rank">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Zelenac"/>
        <xs:enumeration value="Kadet"/>
        <xs:enumeration value="Pilot"/>
        <xs:enumeration value="Kapitan"/>
        <xs:enumeration value="Eso"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="rating">
    <xs:complexType>
      <xs:attribute name="ranger_body" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="vesmirna_lod">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="parametry"/>
      </xs:sequence>
      <xs:attribute name="kapacita" type="xs:integer" use="optional"/>
      <xs:attribute name="typ_trupu" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="role">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Ranger"/>
        <xs:enumeration value="Obchodnik"/>
        <xs:enumeration value="Diplomat"/>
        <xs:enumeration value="Korzar"/>
        <xs:enumeration value="Pirat"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="parametry">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="typ" type="xs:string"/>
        <xs:element name="rychlost" type="xs:integer"/>
        <xs:element name="velikost_skoku" type="xs:integer"/>
        <xs:element name="stity" type="xs:integer"/>
        <xs:element name="pocet_slotu_na_zbrane" type="xs:integer"/>
        <xs:element name="droid" type="xs:boolean"/>
        <xs:element name="jerab" type="xs:boolean"/>
        <xs:element name="generator" type="xs:boolean"/>
        <xs:element name="radar" type="xs:boolean"/>
        <xs:element name="scaner" type="xs:boolean"/>
        <xs:element name="afterburner" type="xs:boolean"/>
        <xs:element name="sloty_na_artefakty" type="xs:decimal"/>
        <xs:element name="cena" type="xs:integer"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vitjasek/Znackovaci_jazyky/SR_xml.xml
<?xml version="1.0" encoding="UTF-8"?>

<vesmir
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation='SR_schema.xsd' pocet_sektoru="2">

  <sektor nazev_sektoru="Milky Way" pocet_systemu="2">
    <system nazev_systemu="Slunecni soustava" pocet_planet="9">
      <planeta nazev_planety="Merkur" pocet_obyvatel="0">
      </planeta>

      <planeta nazev_planety="Venuše" pocet_obyvatel="5000000000">
        <obyvatele vstah_k_pilotovi="Přátelský">
          <rasa>Člověk</rasa>
        </obyvatele>
        <politika>Anarchie</politika>
        <zamereni>Zemedelstvi</zamereni>
      </planeta>

      <planeta nazev_planety="Země" pocet_obyvatel="10000000000">
        <obyvatele vstah_k_pilotovi="Přátelský">
          <rasa>Člověk</rasa>
        </obyvatele>
        <politika>Demokracie</politika>
        <zamereni>Prumysl</zamereni>
        <pilot>
          <jmeno>Rampa McQuack</jmeno>
          <rank>Zelenac</rank>
          <rasa>Člověk</rasa>
          <rating ranger_body="150"></rating>
          <role>Ranger</role>
          <vesmirna_lod kapacita="350" typ_trupu="Ranger hull">
            <parametry>
              <afterburner>true</afterburner>
              <cena>50000</cena>
              <droid>true</droid>
              <generator>true</generator>
              <jerab>true</jerab>
              <pocet_slotu_na_zbrane>3</pocet_slotu_na_zbrane>
              <radar>true</radar>
              <rychlost>400</rychlost>
              <scaner>true</scaner>
              <sloty_na_artefakty>3</sloty_na_artefakty>
              <stity>20</stity>
              <typ>clasic rookie ranger hull</typ>
              <velikost_skoku>20</velikost_skoku>
            </parametry>
          </vesmirna_lod>
        </pilot>
      </planeta>

      <planeta nazev_planety="Mars" pocet_obyvatel="6000000000">
        <obyvatele vstah_k_pilotovi="neutrální">
          <rasa>Člověk</rasa>
        </obyvatele>
        <politika>Demokracie</politika>
        <zamereni>Prumysl</zamereni>
      </planeta>

      <pilot>
        <jmeno>Rimmer</jmeno>
        <rank>Eso</rank>
        <rasa>Člověk</rasa>
        <rating ranger_body="10000"></rating>
        <role>Ranger</role>
        <vesmirna_lod kapacita="1000" typ_trupu="Custom ranger ACE hull">
          <parametry>
            <afterburner>true</afterburner>
            <cena>10000000</cena>
            <droid>true</droid>
            <generator>true</generator>
            <jerab>true</jerab>
            <pocet_slotu_na_zbrane>5</pocet_slotu_na_zbrane>
            <radar>true</radar>
            <rychlost>1200</rychlost>
            <scaner>true</scaner>
            <sloty_na_artefakty>4</sloty_na_artefakty>
            <stity>70</stity>
            <typ>Special ranger hull, custom shop</typ>
            <velikost_skoku>52</velikost_skoku>
          </parametry>
        </vesmirna_lod>
      </pilot>

      <planeta nazev_planety="Jupiter" pocet_obyvatel="0"></planeta>
      <planeta nazev_planety="Saturn" pocet_obyvatel="0"></planeta>
      <planeta nazev_planety="Uran" pocet_obyvatel="0"></planeta>
      <planeta nazev_planety="Neptun" pocet_obyvatel="0"></planeta>
      <planeta nazev_planety="Pluto" pocet_obyvatel="0"></planeta>
    </system>

    <system nazev_systemu="Beetlegeuse" pocet_planet="3">
      <planeta nazev_planety="Kappa" pocet_obyvatel="0"></planeta>
      <planeta nazev_planety="Gamma" pocet_obyvatel="800000000">
        <obyvatele vstah_k_pilotovi="přátelský">
          <rasa>Galian</rasa>
        </obyvatele>
        <politika>Monarchie</politika>
        <zamereni>Prumysl</zamereni>
      </planeta>
      <planeta nazev_planety="Omega" pocet_obyvatel="0"></planeta>
    </system>
  </sektor>

  <sektor nazev_sektoru="Proxima" pocet_systemu="1">
    <system nazev_systemu="Proxima Centauri" pocet_planet="2">
      <planeta nazev_planety="XJ105" pocet_obyvatel="10000000000">
        <obyvatele vstah_k_pilotovi="Nepřátelský">
          <rasa>Maloc</rasa>
        </obyvatele>
        <politika>Diktatura</politika>
        <zamereni>Zemedelstvi</zamereni>
        <pilot>
          <jmeno>KIFF</jmeno>
          <rank>Pilot</rank>
          <rasa>Maloc</rasa>
          <rating ranger_body="1500"></rating>
          <role>Korzar</role>
          <vesmirna_lod kapacita="400" typ_trupu="Military Maloc">
            <parametry>
              <afterburner>false</afterburner>
              <cena>80000</cena>
              <droid>true</droid>
              <generator>true</generator>
              <jerab>false</jerab>
              <pocet_slotu_na_zbrane>5</pocet_slotu_na_zbrane>
              <radar>true</radar>
              <rychlost>600</rychlost>
              <scaner>false</scaner>
              <sloty_na_artefakty>0</sloty_na_artefakty>
              <stity>40</stity>
              <typ>Clasic military Maloc ship</typ>
              <velikost_skoku>40</velikost_skoku>
            </parametry>
          </vesmirna_lod>
        </pilot>
      </planeta>

      <planeta nazev_planety="XJ106" pocet_obyvatel="0"></planeta>
    </system>
  </sektor>

</vesmir>
